@echo off
:: setup_task_scheduler.bat
:: PC起動時・スリープ復帰時に claim_slot.bat を自動起動するタスクを登録する。
:: 管理者として実行してください。

setlocal
set "TASK_NAME=Hermes-Claim-OCI"
set "BAT_PATH=%~dp0claim_slot.bat"
set "WRAPPER=%~dp0task_start.ps1"

echo.
echo ════════════════════════════════════════════
echo   Hermes OCI  —  タスクスケジューラ設定
echo ════════════════════════════════════════════
echo.

:: 既存タスクを削除
schtasks /delete /tn "%TASK_NAME%" /f >nul 2>&1

:: ── PowerShellラッパーを生成 ──
:: （claim_slot.bat が既に動いていたら二重起動しない）
(
echo # task_start.ps1  — generated by setup_task_scheduler.bat
echo $ScriptDir  = Split-Path -Parent $MyInvocation.MyCommand.Path
echo $StatusFile = Join-Path $ScriptDir "status.json"
echo $BatFile    = Join-Path $ScriptDir "claim_slot.bat"
echo.
echo # 既に動いているか確認（last_update が5分以内なら起動しない）
echo $alreadyRunning = $false
echo if (Test-Path $StatusFile) {
echo     try {
echo         $s = Get-Content $StatusFile -Raw ^| ConvertFrom-Json
echo         if ($s.state -eq "success") { exit 0 }   # 取得済みなら起動不要
echo         $last = [datetime]::ParseExact($s.last_update, "yyyy-MM-dd HH:mm:ss", $null^)
echo         if (((Get-Date^) - $last^).TotalMinutes -lt 5) { $alreadyRunning = $true }
echo     } catch {}
echo }
echo.
echo if (-not $alreadyRunning) {
echo     Start-Process -FilePath $BatFile -WindowStyle Normal
echo }
) > "%WRAPPER%"

:: ── XMLでタスク登録（複数トリガー：ログオン時 + スリープ復帰後2分） ──
set "TASK_XML=%TEMP%\hermes_task.xml"

(
echo ^<?xml version="1.0" encoding="UTF-16"?^>
echo ^<Task version="1.3" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task"^>
echo   ^<Triggers^>
echo     ^<LogonTrigger^>
echo       ^<Enabled^>true^</Enabled^>
echo       ^<Delay^>PT1M^</Delay^>
echo     ^</LogonTrigger^>
echo     ^<SessionStateChangeTrigger^>
echo       ^<StateChange^>RemoteConnect^</StateChange^>
echo       ^<Enabled^>true^</Enabled^>
echo       ^<Delay^>PT1M^</Delay^>
echo     ^</SessionStateChangeTrigger^>
echo   ^</Triggers^>
echo   ^<Principals^>
echo     ^<Principal id="Author"^>
echo       ^<LogonType^>InteractiveToken^</LogonType^>
echo       ^<RunLevel^>LeastPrivilege^</RunLevel^>
echo     ^</Principal^>
echo   ^</Principals^>
echo   ^<Settings^>
echo     ^<MultipleInstancesPolicy^>IgnoreNew^</MultipleInstancesPolicy^>
echo     ^<DisallowStartIfOnBatteries^>false^</DisallowStartIfOnBatteries^>
echo     ^<StopIfGoingOnBatteries^>false^</StopIfGoingOnBatteries^>
echo     ^<ExecutionTimeLimit^>PT0S^</ExecutionTimeLimit^>
echo     ^<Enabled^>true^</Enabled^>
echo   ^</Settings^>
echo   ^<Actions^>
echo     ^<Exec^>
echo       ^<Command^>powershell.exe^</Command^>
echo       ^<Arguments^>-WindowStyle Hidden -ExecutionPolicy Bypass -File "%WRAPPER%"^</Arguments^>
echo       ^<WorkingDirectory^>%~dp0^</WorkingDirectory^>
echo     ^</Exec^>
echo   ^</Actions^>
echo ^</Task^>
) > "%TASK_XML%"

schtasks /create /tn "%TASK_NAME%" /xml "%TASK_XML%" /f
del "%TASK_XML%" >nul 2>&1

echo.
if %errorlevel%==0 (
    echo  [OK] タスク "%TASK_NAME%" を登録しました。
    echo.
    echo  ✅ PCログイン時に自動起動します。
    echo  ✅ 既に動いていれば二重起動はしません。
    echo  ✅ 取得完了後はタスクを手動で削除してください。
    echo      schtasks /delete /tn "%TASK_NAME%" /f
) else (
    echo  [ERROR] タスク登録に失敗しました。
    echo  「管理者として実行」で再試行してください。
)

echo.
pause
endlocal
